version: '3.8'

services:
  bitcoin_miner:
    image: mybitcoinimage
    build:
      context: BTCNode
      dockerfile: ./Dockerfile
    environment:
      - RPCUSER=myrpcuser
      - RPCPASSWORD=myrpcpassword
      - RPCPORT=8332
      - NETWORK=regtest 
      - MINE=1
      - ADDNODES=bitcoin_node1 bitcoin_node2
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - ./btcdata/bitcoin-data-miner:/bitcoin
    networks:
      - bitcoin_net

  bitcoin_node1:
    image: mybitcoinimage
    environment:
      - RPCUSER=myrpcuser
      - RPCPASSWORD=myrpcpassword
      - RPCPORT=18332
      - NETWORK=regtest 
      - ADDNODES=bitcoin_miner
    ports:
      - "18332:18332"
      - "18333:18333"
    volumes:
      - ./btcdata/bitcoin-data-node1:/bitcoin
    networks:
      - bitcoin_net

  bitcoin_node2:
    image: mybitcoinimage
    environment:
      - RPCUSER=myrpcuser
      - RPCPASSWORD=myrpcpassword
      - RPCPORT=28332
      - NETWORK=regtest 
      - ADDNODES=bitcoin_miner
    ports:
      - "28332:28332"
      - "28333:28333"
    volumes:
      - ./btcdata/bitcoin-data-node2:/bitcoin
    networks:
      - bitcoin_net


  
  wallet_miner:
    image: mybitcoinwalletimage
    
    build:
      context: BTCWebWallet
      dockerfile: ./Dockerfile

    environment:
      - RPC__HOST=bitcoin_miner
      - RPC__PORT=8332
      - RPC__USER=myrpcuser
      - RPC__PWD=myrpcpassword
    ports:
      - "9998:9999"
    depends_on:
      - bitcoin_miner
    networks:
      - bitcoin_net

  wallet_node1:
    image: mybitcoinwalletimage

    environment:
      - RPC__HOST=bitcoin_node1
      - RPC__PORT=18332
      - RPC__USER=myrpcuser
      - RPC__PWD=myrpcpassword
    ports:
      - "19998:9999"
    networks:
      - bitcoin_net
    
    depends_on:
      - wallet_miner
      - bitcoin_node1

  wallet_node2:
    image: mybitcoinwalletimage

    environment:
      - RPC__HOST=bitcoin_node2
      - RPC__PORT=28332
      - RPC__USER=myrpcuser
      - RPC__PWD=myrpcpassword
    ports:
      - "29998:9999"
    networks:
      - bitcoin_net
    depends_on:
      - wallet_miner
      - bitcoin_node2
  explorer:
    build: 
      context: btc-rpc-explorer
      dockerfile: Dockerfile
    environment:
      - BTCEXP_BITCOIND_URI=bitcoin://myrpcuser:myrpcpassword@bitcoin_node2:28332
      - BTCEXP_HOST=0.0.0.0
    ports:
      - "29988:3002"
    networks:
      - bitcoin_net

networks:
  bitcoin_net:
    driver: bridge